//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILRLegacy.DataStore.ILR1718EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEC_Cases
    {
        public string LearnRefNumber { get; set; }
        public Nullable<int> UKPRN { get; set; }
        public string CaseData { get; set; }
    }
}
