//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILRLegacy.DataStore.ILR1718EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALB_LearningDelivery
    {
        public int UKPRN { get; set; }
        public string LearnRefNumber { get; set; }
        public int AimSeqNumber { get; set; }
        public Nullable<bool> Achieved { get; set; }
        public Nullable<int> ActualNumInstalm { get; set; }
        public Nullable<bool> AdvLoan { get; set; }
        public Nullable<System.DateTime> ApplicFactDate { get; set; }
        public string ApplicProgWeightFact { get; set; }
        public Nullable<decimal> AreaCostFactAdj { get; set; }
        public Nullable<decimal> AreaCostInstalment { get; set; }
        public string FundLine { get; set; }
        public Nullable<bool> FundStart { get; set; }
        public Nullable<System.DateTime> LiabilityDate { get; set; }
        public Nullable<bool> LoanBursAreaUplift { get; set; }
        public Nullable<bool> LoanBursSupp { get; set; }
        public Nullable<int> OutstndNumOnProgInstalm { get; set; }
        public Nullable<int> PlannedNumOnProgInstalm { get; set; }
        public Nullable<decimal> WeightedRate { get; set; }
    }
}
