//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILRLegacy.DataStore.ILR1718EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFA_Learner
    {
        public int UKPRN { get; set; }
        public string LearnRefNumber { get; set; }
        public Nullable<int> AcadMonthPayment { get; set; }
        public Nullable<bool> AcadProg { get; set; }
        public Nullable<int> ActualDaysILCurrYear { get; set; }
        public Nullable<decimal> AreaCostFact1618Hist { get; set; }
        public Nullable<decimal> Block1DisadvUpliftNew { get; set; }
        public Nullable<decimal> Block2DisadvElementsNew { get; set; }
        public string ConditionOfFundingEnglish { get; set; }
        public string ConditionOfFundingMaths { get; set; }
        public Nullable<int> CoreAimSeqNumber { get; set; }
        public Nullable<decimal> FullTimeEquiv { get; set; }
        public string FundLine { get; set; }
        public Nullable<System.DateTime> LearnerActEndDate { get; set; }
        public Nullable<System.DateTime> LearnerPlanEndDate { get; set; }
        public Nullable<System.DateTime> LearnerStartDate { get; set; }
        public Nullable<decimal> NatRate { get; set; }
        public Nullable<decimal> OnProgPayment { get; set; }
        public Nullable<int> PlannedDaysILCurrYear { get; set; }
        public Nullable<decimal> ProgWeightHist { get; set; }
        public Nullable<decimal> ProgWeightNew { get; set; }
        public Nullable<decimal> PrvDisadvPropnHist { get; set; }
        public Nullable<decimal> PrvHistLrgProgPropn { get; set; }
        public Nullable<decimal> PrvRetentFactHist { get; set; }
        public string RateBand { get; set; }
        public Nullable<decimal> RetentNew { get; set; }
        public Nullable<bool> StartFund { get; set; }
        public Nullable<int> ThresholdDays { get; set; }
    }
}
