//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILRLegacy.DataStore.ILR1718EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ILR1718_Rulebase : DbContext
    {
        public ILR1718_Rulebase()
            : base("name=ILR1718_Rulebase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AEC_ApprenticeshipPriceEpisode> AEC_ApprenticeshipPriceEpisode { get; set; }
        public virtual DbSet<AEC_ApprenticeshipPriceEpisode_Period> AEC_ApprenticeshipPriceEpisode_Period { get; set; }
        public virtual DbSet<AEC_ApprenticeshipPriceEpisode_PeriodisedValues> AEC_ApprenticeshipPriceEpisode_PeriodisedValues { get; set; }
        public virtual DbSet<AEC_HistoricEarningOutput> AEC_HistoricEarningOutput { get; set; }
        public virtual DbSet<AEC_LearningDelivery> AEC_LearningDelivery { get; set; }
        public virtual DbSet<AEC_LearningDelivery_Period> AEC_LearningDelivery_Period { get; set; }
        public virtual DbSet<AEC_LearningDelivery_PeriodisedTextValues> AEC_LearningDelivery_PeriodisedTextValues { get; set; }
        public virtual DbSet<AEC_LearningDelivery_PeriodisedValues> AEC_LearningDelivery_PeriodisedValues { get; set; }
        public virtual DbSet<ALB_Cases> ALB_Cases { get; set; }
        public virtual DbSet<ALB_global> ALB_global { get; set; }
        public virtual DbSet<ALB_Learner_Period> ALB_Learner_Period { get; set; }
        public virtual DbSet<ALB_Learner_PeriodisedValues> ALB_Learner_PeriodisedValues { get; set; }
        public virtual DbSet<ALB_LearningDelivery> ALB_LearningDelivery { get; set; }
        public virtual DbSet<ALB_LearningDelivery_Period> ALB_LearningDelivery_Period { get; set; }
        public virtual DbSet<ALB_LearningDelivery_PeriodisedValues> ALB_LearningDelivery_PeriodisedValues { get; set; }
        public virtual DbSet<DV_Learner> DV_Learner { get; set; }
        public virtual DbSet<DV_LearningDelivery> DV_LearningDelivery { get; set; }
        public virtual DbSet<EFA_Cases> EFA_Cases { get; set; }
        public virtual DbSet<EFA_global> EFA_global { get; set; }
        public virtual DbSet<EFA_Learner> EFA_Learner { get; set; }
        public virtual DbSet<EFA_SFA_Cases> EFA_SFA_Cases { get; set; }
        public virtual DbSet<EFA_SFA_global> EFA_SFA_global { get; set; }
        public virtual DbSet<EFA_SFA_Learner_Period> EFA_SFA_Learner_Period { get; set; }
        public virtual DbSet<EFA_SFA_Learner_PeriodisedValues> EFA_SFA_Learner_PeriodisedValues { get; set; }
        public virtual DbSet<ESF_DPOutcome> ESF_DPOutcome { get; set; }
        public virtual DbSet<ESF_LearningDelivery> ESF_LearningDelivery { get; set; }
        public virtual DbSet<ESF_LearningDeliveryDeliverable> ESF_LearningDeliveryDeliverable { get; set; }
        public virtual DbSet<ESF_LearningDeliveryDeliverable_Period> ESF_LearningDeliveryDeliverable_Period { get; set; }
        public virtual DbSet<ESF_LearningDeliveryDeliverable_PeriodisedValues> ESF_LearningDeliveryDeliverable_PeriodisedValues { get; set; }
        public virtual DbSet<ESFVAL_Cases> ESFVAL_Cases { get; set; }
        public virtual DbSet<SFA_Cases> SFA_Cases { get; set; }
        public virtual DbSet<SFA_global> SFA_global { get; set; }
        public virtual DbSet<SFA_LearningDelivery> SFA_LearningDelivery { get; set; }
        public virtual DbSet<SFA_LearningDelivery_Period> SFA_LearningDelivery_Period { get; set; }
        public virtual DbSet<SFA_LearningDelivery_PeriodisedValues> SFA_LearningDelivery_PeriodisedValues { get; set; }
        public virtual DbSet<TBL_Cases> TBL_Cases { get; set; }
        public virtual DbSet<TBL_global> TBL_global { get; set; }
        public virtual DbSet<TBL_LearningDelivery> TBL_LearningDelivery { get; set; }
        public virtual DbSet<TBL_LearningDelivery_Period> TBL_LearningDelivery_Period { get; set; }
        public virtual DbSet<TBL_LearningDelivery_PeriodisedValues> TBL_LearningDelivery_PeriodisedValues { get; set; }
        public virtual DbSet<VAL_Cases> VAL_Cases { get; set; }
        public virtual DbSet<VAL_global> VAL_global { get; set; }
        public virtual DbSet<VAL_Learner> VAL_Learner { get; set; }
        public virtual DbSet<VAL_LearningDelivery> VAL_LearningDelivery { get; set; }
        public virtual DbSet<VALDP_Cases> VALDP_Cases { get; set; }
        public virtual DbSet<VALDP_global> VALDP_global { get; set; }
        public virtual DbSet<AEC_Cases> AEC_Cases { get; set; }
        public virtual DbSet<DV_Cases> DV_Cases { get; set; }
        public virtual DbSet<ESF_Cases> ESF_Cases { get; set; }
        public virtual DbSet<VAL_ValidationError> VAL_ValidationError { get; set; }
        public virtual DbSet<VALDP_ValidationError> VALDP_ValidationError { get; set; }
        public virtual DbSet<VALFD_ValidationError> VALFD_ValidationError { get; set; }
    }
}
