//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILRLegacy.DataStore.ILR1718EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFA_LearningDelivery_Period
    {
        public int UKPRN { get; set; }
        public string LearnRefNumber { get; set; }
        public int AimSeqNumber { get; set; }
        public int Period { get; set; }
        public Nullable<decimal> AchievePayment { get; set; }
        public Nullable<decimal> AchievePayPct { get; set; }
        public Nullable<decimal> AchievePayPctTrans { get; set; }
        public Nullable<decimal> BalancePayment { get; set; }
        public Nullable<decimal> BalancePaymentUncapped { get; set; }
        public Nullable<decimal> BalancePct { get; set; }
        public Nullable<decimal> BalancePctTrans { get; set; }
        public Nullable<decimal> EmpOutcomePay { get; set; }
        public Nullable<decimal> EmpOutcomePct { get; set; }
        public Nullable<decimal> EmpOutcomePctTrans { get; set; }
        public Nullable<int> InstPerPeriod { get; set; }
        public Nullable<bool> LearnSuppFund { get; set; }
        public Nullable<decimal> LearnSuppFundCash { get; set; }
        public Nullable<decimal> OnProgPayment { get; set; }
        public Nullable<decimal> OnProgPaymentUncapped { get; set; }
        public Nullable<decimal> OnProgPayPct { get; set; }
        public Nullable<decimal> OnProgPayPctTrans { get; set; }
        public Nullable<int> TransInstPerPeriod { get; set; }
    }
}
