//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILRLegacy.DataStore._1617EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_LearningDelivery
    {
        public string LearnRefNumber { get; set; }
        public int AimSeqNumber { get; set; }
        public long Ukprn { get; set; }
        public long Uln { get; set; }
        public string NiNumber { get; set; }
        public Nullable<long> StdCode { get; set; }
        public Nullable<int> ProgType { get; set; }
        public Nullable<int> FworkCode { get; set; }
        public Nullable<int> PwayCode { get; set; }
        public int NegotiatedPrice { get; set; }
        public System.DateTime LearnStartDate { get; set; }
        public Nullable<System.DateTime> OrigLearnStartDate { get; set; }
        public System.DateTime LearnPlanEndDate { get; set; }
        public Nullable<System.DateTime> LearnActEndDate { get; set; }
        public decimal MonthlyInstallment { get; set; }
        public decimal MonthlyInstallmentUncapped { get; set; }
        public decimal CompletionPayment { get; set; }
        public decimal CompletionPaymentUncapped { get; set; }
    }
}
