//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILRLegacy.DataStore._1617EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AE_LearningDelivery_Period
    {
        public long Ukprn { get; set; }
        public string LearnRefNumber { get; set; }
        public int AimSeqNumber { get; set; }
        public int Period { get; set; }
        public Nullable<decimal> ProgrammeAimOnProgPayment { get; set; }
        public Nullable<decimal> ProgrammeAimCompletionPayment { get; set; }
        public Nullable<decimal> ProgrammeAimBalPayment { get; set; }
    }
}
