//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILRLegacy.DataStore._1617EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEC_ApprenticeshipPriceEpisode
    {
        public int UKPRN { get; set; }
        public string LearnRefNumber { get; set; }
        public string PriceEpisodeIdentifier { get; set; }
        public Nullable<System.DateTime> EpisodeEffectiveTNPStartDate { get; set; }
        public Nullable<System.DateTime> EpisodeStartDate { get; set; }
        public Nullable<System.DateTime> PriceEpisodeActualEndDate { get; set; }
        public Nullable<int> PriceEpisodeActualInstalments { get; set; }
        public Nullable<int> PriceEpisodeAimSeqNumber { get; set; }
        public Nullable<decimal> PriceEpisodeCappedRemainingTNPAmount { get; set; }
        public Nullable<bool> PriceEpisodeCompleted { get; set; }
        public Nullable<decimal> PriceEpisodeCompletionElement { get; set; }
        public Nullable<decimal> PriceEpisodeExpectedTotalMonthlyValue { get; set; }
        public Nullable<System.DateTime> PriceEpisodeFirstAdditionalPaymentThresholdDate { get; set; }
        public Nullable<decimal> PriceEpisodeInstalmentValue { get; set; }
        public Nullable<System.DateTime> PriceEpisodePlannedEndDate { get; set; }
        public Nullable<int> PriceEpisodePlannedInstalments { get; set; }
        public Nullable<decimal> PriceEpisodePreviousEarnings { get; set; }
        public Nullable<decimal> PriceEpisodeRemainingAmountWithinUpperLimit { get; set; }
        public Nullable<decimal> PriceEpisodeRemainingTNPAmount { get; set; }
        public Nullable<System.DateTime> PriceEpisodeSecondAdditionalPaymentThresholdDate { get; set; }
        public Nullable<decimal> PriceEpisodeTotalEarnings { get; set; }
        public Nullable<decimal> PriceEpisodeTotalTNPPrice { get; set; }
        public Nullable<decimal> PriceEpisodeUpperBandLimit { get; set; }
        public Nullable<decimal> PriceEpisodeUpperLimitAdjustment { get; set; }
        public Nullable<decimal> TNP1 { get; set; }
        public Nullable<decimal> TNP2 { get; set; }
        public Nullable<decimal> TNP3 { get; set; }
        public Nullable<decimal> TNP4 { get; set; }
        public string PriceEpisodeContractType { get; set; }
        public string PriceEpisodeFundLineType { get; set; }
        public Nullable<decimal> PriceEpisodePreviousEarningsSameProvider { get; set; }
    }
}
