//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILRLegacy.DataStore._1617EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEC_LearningDelivery
    {
        public int UKPRN { get; set; }
        public string LearnRefNumber { get; set; }
        public int AimSeqNumber { get; set; }
        public Nullable<int> ActualDaysIL { get; set; }
        public Nullable<int> ActualNumInstalm { get; set; }
        public Nullable<System.DateTime> AdjStartDate { get; set; }
        public Nullable<int> AgeAtProgStart { get; set; }
        public Nullable<System.DateTime> AppAdjLearnStartDate { get; set; }
        public Nullable<System.DateTime> ApplicCompDate { get; set; }
        public Nullable<decimal> CombinedAdjProp { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<decimal> DisUpFactAdj { get; set; }
        public Nullable<System.DateTime> FirstIncentiveThresholdDate { get; set; }
        public Nullable<bool> FundStart { get; set; }
        public Nullable<decimal> LDApplic1618FrameworkUpliftBalancingValue { get; set; }
        public Nullable<decimal> LDApplic1618FrameworkUpliftCompElement { get; set; }
        public Nullable<decimal> LDApplic1618FRameworkUpliftCompletionValue { get; set; }
        public Nullable<decimal> LDApplic1618FrameworkUpliftMonthInstalVal { get; set; }
        public Nullable<decimal> LDApplic1618FrameworkUpliftPrevEarnings { get; set; }
        public Nullable<decimal> LDApplic1618FrameworkUpliftRemainingAmount { get; set; }
        public Nullable<decimal> LDApplic1618FrameworkUpliftTotalActEarnings { get; set; }
        public string LearnAimRef { get; set; }
        public Nullable<bool> LearnDel1618AtStart { get; set; }
        public Nullable<int> LearnDelAppAccDaysIL { get; set; }
        public Nullable<decimal> LearnDelApplicDisadvAmount { get; set; }
        public Nullable<decimal> LearnDelApplicEmp1618Incentive { get; set; }
        public Nullable<System.DateTime> LearnDelApplicEmpDate { get; set; }
        public Nullable<decimal> LearnDelApplicProv1618FrameworkUplift { get; set; }
        public Nullable<decimal> LearnDelApplicProv1618Incentive { get; set; }
        public Nullable<decimal> LearnDelApplicTot1618Incentive { get; set; }
        public Nullable<int> LearnDelAppPrevAccDaysIL { get; set; }
        public Nullable<int> LearnDelDaysIL { get; set; }
        public Nullable<decimal> LearnDelDisadAmount { get; set; }
        public Nullable<bool> LearnDelEligDisadvPayment { get; set; }
        public Nullable<int> LearnDelHistDaysThisApp { get; set; }
        public string LearnDelInitialFundLineType { get; set; }
        public Nullable<bool> LearnDelSEMContWaiver { get; set; }
        public Nullable<decimal> MathEngAimValue { get; set; }
        public Nullable<int> OutstandNumOnProgInstalm { get; set; }
        public Nullable<int> PlannedNumOnProgInstalm { get; set; }
        public Nullable<int> PlannedTotalDaysIL { get; set; }
        public Nullable<System.DateTime> SecondIncentiveThresholdDate { get; set; }
        public Nullable<int> ThresholdDays { get; set; }
        public Nullable<System.DateTime> AppAdjLearnStartDateMatchPathway { get; set; }
        public Nullable<decimal> LearnDelHistProgEarnings { get; set; }
        public Nullable<decimal> LDApplic1618FrameworkUpliftPrevEarningsStage1 { get; set; }
        public Nullable<int> LearnDelEmpIdFirstAdditionalPaymentThreshold { get; set; }
        public Nullable<int> LearnDelEmpIdSecondAdditionalPaymentThreshold { get; set; }
    }
}
