//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILRLegacy.DataStore._1617EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFA_SFA_Learner_PeriodisedValues
    {
        public int UKPRN { get; set; }
        public string LearnRefNumber { get; set; }
        public string AttributeName { get; set; }
        public Nullable<decimal> Period_1 { get; set; }
        public Nullable<decimal> Period_2 { get; set; }
        public Nullable<decimal> Period_3 { get; set; }
        public Nullable<decimal> Period_4 { get; set; }
        public Nullable<decimal> Period_5 { get; set; }
        public Nullable<decimal> Period_6 { get; set; }
        public Nullable<decimal> Period_7 { get; set; }
        public Nullable<decimal> Period_8 { get; set; }
        public Nullable<decimal> Period_9 { get; set; }
        public Nullable<decimal> Period_10 { get; set; }
        public Nullable<decimal> Period_11 { get; set; }
        public Nullable<decimal> Period_12 { get; set; }
    }
}
