//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILRLegacy.DataStore._1617EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ILR1617_DataStoreEntities : DbContext
    {
        public ILR1617_DataStoreEntities()
            : base("name=ILR1617_DataStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AE_LearningDelivery> AE_LearningDelivery { get; set; }
        public virtual DbSet<AE_LearningDelivery_Period> AE_LearningDelivery_Period { get; set; }
        public virtual DbSet<AE_LearningDelivery_PeriodisedValues> AE_LearningDelivery_PeriodisedValues { get; set; }
        public virtual DbSet<AEC_ApprenticeshipPriceEpisode> AEC_ApprenticeshipPriceEpisode { get; set; }
        public virtual DbSet<AEC_ApprenticeshipPriceEpisode_Period> AEC_ApprenticeshipPriceEpisode_Period { get; set; }
        public virtual DbSet<AEC_ApprenticeshipPriceEpisode_PeriodisedValues> AEC_ApprenticeshipPriceEpisode_PeriodisedValues { get; set; }
        public virtual DbSet<AEC_LearningDelivery> AEC_LearningDelivery { get; set; }
        public virtual DbSet<AEC_LearningDelivery_Period> AEC_LearningDelivery_Period { get; set; }
        public virtual DbSet<AEC_LearningDelivery_PeriodisedTextValues> AEC_LearningDelivery_PeriodisedTextValues { get; set; }
        public virtual DbSet<AEC_LearningDelivery_PeriodisedValues> AEC_LearningDelivery_PeriodisedValues { get; set; }
        public virtual DbSet<ALB_global> ALB_global { get; set; }
        public virtual DbSet<ALB_Learner_Period> ALB_Learner_Period { get; set; }
        public virtual DbSet<ALB_Learner_PeriodisedValues> ALB_Learner_PeriodisedValues { get; set; }
        public virtual DbSet<ALB_LearningDelivery> ALB_LearningDelivery { get; set; }
        public virtual DbSet<ALB_LearningDelivery_Period> ALB_LearningDelivery_Period { get; set; }
        public virtual DbSet<ALB_LearningDelivery_PeriodisedValues> ALB_LearningDelivery_PeriodisedValues { get; set; }
        public virtual DbSet<DV_global> DV_global { get; set; }
        public virtual DbSet<DV_Learner> DV_Learner { get; set; }
        public virtual DbSet<DV_LearningDelivery> DV_LearningDelivery { get; set; }
        public virtual DbSet<EFA_global> EFA_global { get; set; }
        public virtual DbSet<EFA_Learner> EFA_Learner { get; set; }
        public virtual DbSet<EFA_SFA_global> EFA_SFA_global { get; set; }
        public virtual DbSet<EFA_SFA_Learner_Period> EFA_SFA_Learner_Period { get; set; }
        public virtual DbSet<EFA_SFA_Learner_PeriodisedValues> EFA_SFA_Learner_PeriodisedValues { get; set; }
        public virtual DbSet<ESF_DPOutcome> ESF_DPOutcome { get; set; }
        public virtual DbSet<ESF_global> ESF_global { get; set; }
        public virtual DbSet<ESF_LearningDelivery> ESF_LearningDelivery { get; set; }
        public virtual DbSet<ESF_LearningDeliveryDeliverable> ESF_LearningDeliveryDeliverable { get; set; }
        public virtual DbSet<ESF_LearningDeliveryDeliverable_Period> ESF_LearningDeliveryDeliverable_Period { get; set; }
        public virtual DbSet<ESF_LearningDeliveryDeliverable_PeriodisedValues> ESF_LearningDeliveryDeliverable_PeriodisedValues { get; set; }
        public virtual DbSet<ESFVAL_global> ESFVAL_global { get; set; }
        public virtual DbSet<SFA_global> SFA_global { get; set; }
        public virtual DbSet<SFA_LearningDelivery> SFA_LearningDelivery { get; set; }
        public virtual DbSet<SFA_LearningDelivery_Period> SFA_LearningDelivery_Period { get; set; }
        public virtual DbSet<SFA_LearningDelivery_PeriodisedValues> SFA_LearningDelivery_PeriodisedValues { get; set; }
        public virtual DbSet<TBL_global> TBL_global { get; set; }
        public virtual DbSet<TBL_LearningDelivery> TBL_LearningDelivery { get; set; }
        public virtual DbSet<TBL_LearningDelivery_Period> TBL_LearningDelivery_Period { get; set; }
        public virtual DbSet<TBL_LearningDelivery_PeriodisedValues> TBL_LearningDelivery_PeriodisedValues { get; set; }
        public virtual DbSet<TBLVAL_global> TBLVAL_global { get; set; }
        public virtual DbSet<VAL_global> VAL_global { get; set; }
        public virtual DbSet<VALDP_global> VALDP_global { get; set; }
        public virtual DbSet<ESFVAL_ValidationError> ESFVAL_ValidationError { get; set; }
        public virtual DbSet<TBLVAL_ValidationError> TBLVAL_ValidationError { get; set; }
        public virtual DbSet<VAL_ValidationError> VAL_ValidationError { get; set; }
        public virtual DbSet<VALDP_ValidationError> VALDP_ValidationError { get; set; }
        public virtual DbSet<VALFD_ValidationError> VALFD_ValidationError { get; set; }
    }
}
