using System;
using System.Collections.Generic;

namespace ESFA.DC.ILRLegacy.DataStore.ILR1617EF
{
    public partial class DvLearningDelivery
    {
        public int Ukprn { get; set; }
        public string LearnRefNumber { get; set; }
        public int AimSeqNumber { get; set; }
        public int? LearnDelAccToApp { get; set; }
        public DateTime? LearnDelAccToAppEmpDate { get; set; }
        public int? LearnDelAccToAppEmpStat { get; set; }
        public decimal? LearnDelAchFullLevel2Pct { get; set; }
        public decimal? LearnDelAchFullLevel3Pct { get; set; }
        public int? LearnDelAchieved { get; set; }
        public int? LearnDelAchievedIy { get; set; }
        public string LearnDelAcMonthYtd { get; set; }
        public int? LearnDelActDaysIlafterCurrAcYr { get; set; }
        public int? LearnDelActDaysIlcurrAcYr { get; set; }
        public int? LearnDelActEndDateOnAfterJan1 { get; set; }
        public int? LearnDelActEndDateOnAfterNov1 { get; set; }
        public int? LearnDelActEndDateOnAfterOct1 { get; set; }
        public int? LearnDelActiveIy { get; set; }
        public int? LearnDelActiveJan { get; set; }
        public int? LearnDelActiveNov { get; set; }
        public int? LearnDelActiveOct { get; set; }
        public int? LearnDelActTotalDaysIl { get; set; }
        public int? LearnDelAdvLoan { get; set; }
        public int? LearnDelAgeAimOrigStart { get; set; }
        public int? LearnDelAgeAtStart { get; set; }
        public int? LearnDelApp { get; set; }
        public int? LearnDelApp1618Fund { get; set; }
        public int? LearnDelApp1925Fund { get; set; }
        public int? LearnDelAppAimType { get; set; }
        public int? LearnDelAppKnowl { get; set; }
        public int? LearnDelAppMainAim { get; set; }
        public int? LearnDelAppNonFund { get; set; }
        public int? LearnDelBasicSkills { get; set; }
        public int? LearnDelBasicSkillsParticipation { get; set; }
        public int? LearnDelBasicSkillsType { get; set; }
        public int? LearnDelCarryIn { get; set; }
        public int? LearnDelClassRm { get; set; }
        public int? LearnDelCompAimApp { get; set; }
        public int? LearnDelCompAimProg { get; set; }
        public int? LearnDelCompleted { get; set; }
        public int? LearnDelCompletedIy { get; set; }
        public decimal? LearnDelCompleteFullLevel2Pct { get; set; }
        public decimal? LearnDelCompleteFullLevel3Pct { get; set; }
        public int? LearnDelEfacoreAim { get; set; }
        public int? LearnDelEmp6MonthAimStart { get; set; }
        public int? LearnDelEmp6MonthProgStart { get; set; }
        public DateTime? LearnDelEmpDateBeforeFdl { get; set; }
        public DateTime? LearnDelEmpDatePriorFdl { get; set; }
        public int? LearnDelEmpId { get; set; }
        public int? LearnDelEmployed { get; set; }
        public int? LearnDelEmpStatFdl { get; set; }
        public int? LearnDelEmpStatPrior { get; set; }
        public int? LearnDelEmpStatPriorFdl { get; set; }
        public int? LearnDelEnhanAppFund { get; set; }
        public decimal? LearnDelFullLevel2AchPct { get; set; }
        public decimal? LearnDelFullLevel2ContPct { get; set; }
        public decimal? LearnDelFullLevel3AchPct { get; set; }
        public decimal? LearnDelFullLevel3ContPct { get; set; }
        public int? LearnDelFuncSkills { get; set; }
        public int? LearnDelFundAgency { get; set; }
        public string LearnDelFundingLineType { get; set; }
        public int? LearnDelFundingSource { get; set; }
        public int? LearnDelFundPrvYr { get; set; }
        public int? LearnDelFundStart { get; set; }
        public int? LearnDelGce { get; set; }
        public int? LearnDelGcse { get; set; }
        public int? LearnDelIlacMonth1 { get; set; }
        public int? LearnDelIlacMonth10 { get; set; }
        public int? LearnDelIlacMonth11 { get; set; }
        public int? LearnDelIlacMonth12 { get; set; }
        public int? LearnDelIlacMonth2 { get; set; }
        public int? LearnDelIlacMonth3 { get; set; }
        public int? LearnDelIlacMonth4 { get; set; }
        public int? LearnDelIlacMonth5 { get; set; }
        public int? LearnDelIlacMonth6 { get; set; }
        public int? LearnDelIlacMonth7 { get; set; }
        public int? LearnDelIlacMonth8 { get; set; }
        public int? LearnDelIlacMonth9 { get; set; }
        public int? LearnDelIlcurrAcYr { get; set; }
        public DateTime? LearnDelIyactEndDate { get; set; }
        public DateTime? LearnDelIyplanEndDate { get; set; }
        public DateTime? LearnDelIystartDate { get; set; }
        public int? LearnDelKeySkills { get; set; }
        public int? LearnDelLargeEmpDiscountId { get; set; }
        public int? LearnDelLargeEmployer { get; set; }
        public DateTime? LearnDelLastEmpDate { get; set; }
        public int? LearnDelLeaveMonth { get; set; }
        public int? LearnDelLenEmp { get; set; }
        public int? LearnDelLenUnemp { get; set; }
        public int? LearnDelLoanBursFund { get; set; }
        public int? LearnDelNotionLevel { get; set; }
        public int? LearnDelNotionLevelV2 { get; set; }
        public int? LearnDelNumHedatasets { get; set; }
        public int? LearnDelOccupAim { get; set; }
        public int? LearnDelOlass { get; set; }
        public int? LearnDelOlasscom { get; set; }
        public int? LearnDelOlasscus { get; set; }
        public DateTime? LearnDelOrigStartDate { get; set; }
        public int? LearnDelPlanDaysIlafterCurrAcYr { get; set; }
        public int? LearnDelPlanDaysIlcurrAcYr { get; set; }
        public int? LearnDelPlanEndBeforeAug1 { get; set; }
        public int? LearnDelPlanEndOnAfterJan1 { get; set; }
        public int? LearnDelPlanEndOnAfterNov1 { get; set; }
        public int? LearnDelPlanEndOnAfterOct1 { get; set; }
        public int? LearnDelPlanTotalDaysIl { get; set; }
        public int? LearnDelPriorEducationStatus { get; set; }
        public int? LearnDelProg { get; set; }
        public int? LearnDelProgAimAch { get; set; }
        public int? LearnDelProgAimApp { get; set; }
        public int? LearnDelProgCompleted { get; set; }
        public int? LearnDelProgCompletedIy { get; set; }
        public DateTime? LearnDelProgStartDate { get; set; }
        public int? LearnDelQcf { get; set; }
        public int? LearnDelQcfcert { get; set; }
        public int? LearnDelQcfdipl { get; set; }
        public int? LearnDelQcftype { get; set; }
        public int? LearnDelRegAim { get; set; }
        public string LearnDelSecSubAreaTier1 { get; set; }
        public string LearnDelSecSubAreaTier2 { get; set; }
        public int? LearnDelSfaapproved { get; set; }
        public int? LearnDelSourceFundEfa { get; set; }
        public int? LearnDelSourceFundSfa { get; set; }
        public int? LearnDelStartBeforeApr1 { get; set; }
        public int? LearnDelStartBeforeAug1 { get; set; }
        public int? LearnDelStartBeforeDec1 { get; set; }
        public int? LearnDelStartBeforeFeb1 { get; set; }
        public int? LearnDelStartBeforeJan1 { get; set; }
        public int? LearnDelStartBeforeJun1 { get; set; }
        public int? LearnDelStartBeforeMar1 { get; set; }
        public int? LearnDelStartBeforeMay1 { get; set; }
        public int? LearnDelStartBeforeNov1 { get; set; }
        public int? LearnDelStartBeforeOct1 { get; set; }
        public int? LearnDelStartBeforeSep1 { get; set; }
        public int? LearnDelStartIy { get; set; }
        public int? LearnDelStartJan1 { get; set; }
        public int? LearnDelStartMonth { get; set; }
        public int? LearnDelStartNov1 { get; set; }
        public int? LearnDelStartOct1 { get; set; }
        public int? LearnDelSuccRateStat { get; set; }
        public int? LearnDelTrainAimType { get; set; }
        public int? LearnDelTransferDiffProvider { get; set; }
        public int? LearnDelTransferDiffProviderGovStrat { get; set; }
        public int? LearnDelTransferProvider { get; set; }
        public int? LearnDelUfIprov { get; set; }
        public int? LearnDelUnempBenFdl { get; set; }
        public int? LearnDelUnempBenPrior { get; set; }
        public int? LearnDelWithdrawn { get; set; }
        public string LearnDelWorkplaceLocPostcode { get; set; }
        public int? ProgAccToApp { get; set; }
        public int? ProgAchieved { get; set; }
        public int? ProgAchievedIy { get; set; }
        public DateTime? ProgActEndDate { get; set; }
        public int? ProgActiveIy { get; set; }
        public int? ProgAgeAtStart { get; set; }
        public int? ProgEarliestAim { get; set; }
        public int? ProgEmployed { get; set; }
        public int? ProgFundPrvYr { get; set; }
        public int? ProgIlcurrAcYear { get; set; }
        public int? ProgLatestAim { get; set; }
        public int? ProgSourceFundEfa { get; set; }
        public int? ProgSourceFundSfa { get; set; }
    }
}
