//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILRLegacy.DataStore.ILR1617EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESF_DPOutcome
    {
        public int UKPRN { get; set; }
        public string LearnRefNumber { get; set; }
        public int OutCode { get; set; }
        public string OutType { get; set; }
        public System.DateTime OutStartDate { get; set; }
        public Nullable<System.DateTime> OutcomeDateForProgression { get; set; }
        public Nullable<bool> PotentialESFProgressionType { get; set; }
        public string ProgressionType { get; set; }
        public Nullable<bool> ReachedSixMonthPoint { get; set; }
        public Nullable<bool> ReachedThreeMonthPoint { get; set; }
        public Nullable<bool> ReachedTwelveMonthPoint { get; set; }
    }
}
