//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILRLegacy.DataStore.ILR1617EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFA_LearningDelivery
    {
        public int UKPRN { get; set; }
        public string LearnRefNumber { get; set; }
        public int AimSeqNumber { get; set; }
        public Nullable<System.DateTime> AchApplicDate { get; set; }
        public Nullable<bool> Achieved { get; set; }
        public Nullable<decimal> AchieveElement { get; set; }
        public Nullable<bool> AchievePayElig { get; set; }
        public Nullable<decimal> AchievePayPctPreTrans { get; set; }
        public Nullable<decimal> AchPayTransHeldBack { get; set; }
        public Nullable<int> ActualDaysIL { get; set; }
        public Nullable<int> ActualNumInstalm { get; set; }
        public Nullable<int> ActualNumInstalmPreTrans { get; set; }
        public Nullable<int> ActualNumInstalmTrans { get; set; }
        public Nullable<System.DateTime> AdjLearnStartDate { get; set; }
        public Nullable<bool> AdltLearnResp { get; set; }
        public Nullable<bool> AdultApp1618Rate { get; set; }
        public Nullable<int> AgeAimStart { get; set; }
        public Nullable<decimal> AimValue { get; set; }
        public Nullable<System.DateTime> AppAdjLearnStartDate { get; set; }
        public Nullable<decimal> AppAgeFact { get; set; }
        public Nullable<bool> AppATAGTA { get; set; }
        public Nullable<bool> AppCompetency { get; set; }
        public Nullable<bool> AppFuncSkill { get; set; }
        public Nullable<decimal> AppFuncSkill1618AdjFact { get; set; }
        public Nullable<bool> AppKnowl { get; set; }
        public Nullable<System.DateTime> AppLearnStartDate { get; set; }
        public Nullable<System.DateTime> ApplicEmpFactDate { get; set; }
        public Nullable<System.DateTime> ApplicFactDate { get; set; }
        public Nullable<System.DateTime> ApplicFundRateDate { get; set; }
        public string ApplicProgWeightFact { get; set; }
        public Nullable<decimal> ApplicUnweightFundRate { get; set; }
        public Nullable<decimal> ApplicWeightFundRate { get; set; }
        public Nullable<bool> AppNonFund { get; set; }
        public Nullable<decimal> AreaCostFactAdj { get; set; }
        public Nullable<int> BalInstalmPreTrans { get; set; }
        public Nullable<decimal> BaseValueUnweight { get; set; }
        public Nullable<decimal> CapFactor { get; set; }
        public Nullable<decimal> DisUpFactAdj { get; set; }
        public Nullable<bool> EmpOutcomePayElig { get; set; }
        public Nullable<decimal> EmpOutcomePctHeldBackTrans { get; set; }
        public Nullable<decimal> EmpOutcomePctPreTrans { get; set; }
        public Nullable<bool> EmpRespOth { get; set; }
        public Nullable<bool> ESOL { get; set; }
        public Nullable<bool> FullyFund { get; set; }
        public string FundLine { get; set; }
        public Nullable<bool> FundStart { get; set; }
        public Nullable<int> LargeEmployerID { get; set; }
        public Nullable<decimal> LargeEmployerSFAFctr { get; set; }
        public Nullable<System.DateTime> LargeEmployerStatusDate { get; set; }
        public Nullable<decimal> LTRCUpliftFctr { get; set; }
        public Nullable<decimal> NonGovCont { get; set; }
        public Nullable<bool> OLASSCustody { get; set; }
        public Nullable<decimal> OnProgPayPctPreTrans { get; set; }
        public Nullable<int> OutstndNumOnProgInstalm { get; set; }
        public Nullable<int> OutstndNumOnProgInstalmTrans { get; set; }
        public Nullable<int> PlannedNumOnProgInstalm { get; set; }
        public Nullable<int> PlannedNumOnProgInstalmTrans { get; set; }
        public Nullable<int> PlannedTotalDaysIL { get; set; }
        public Nullable<int> PlannedTotalDaysILPreTrans { get; set; }
        public Nullable<decimal> PropFundRemain { get; set; }
        public Nullable<decimal> PropFundRemainAch { get; set; }
        public Nullable<bool> PrscHEAim { get; set; }
        public Nullable<bool> Residential { get; set; }
        public Nullable<bool> Restart { get; set; }
        public Nullable<decimal> SpecResUplift { get; set; }
        public Nullable<decimal> StartPropTrans { get; set; }
        public Nullable<int> ThresholdDays { get; set; }
        public Nullable<bool> Traineeship { get; set; }
        public Nullable<bool> Trans { get; set; }
        public Nullable<System.DateTime> TrnAdjLearnStartDate { get; set; }
        public Nullable<bool> TrnWorkPlaceAim { get; set; }
        public Nullable<bool> TrnWorkPrepAim { get; set; }
        public Nullable<decimal> UnWeightedRateFromESOL { get; set; }
        public Nullable<decimal> UnweightedRateFromLARS { get; set; }
        public Nullable<decimal> WeightedRateFromESOL { get; set; }
        public Nullable<decimal> WeightedRateFromLARS { get; set; }
    }
}
