//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILRLegacy.DataStore.ILR1617EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAL_global
    {
        public int UKPRN { get; set; }
        public string EmployerVersion { get; set; }
        public string LARSVersion { get; set; }
        public string OrgVersion { get; set; }
        public string PostcodeVersion { get; set; }
        public string RulebaseVersion { get; set; }
    }
}
