//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILRLegacy.DataStore._1718EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEC_HistoricEarningOutput
    {
        public int UKPRN { get; set; }
        public string LearnRefNumber { get; set; }
        public string AppIdentifierOutput { get; set; }
        public Nullable<bool> AppProgCompletedInTheYearOutput { get; set; }
        public Nullable<int> HistoricDaysInYearOutput { get; set; }
        public Nullable<System.DateTime> HistoricEffectiveTNPStartDateOutput { get; set; }
        public Nullable<int> HistoricEmpIdEndWithinYearOutput { get; set; }
        public Nullable<int> HistoricEmpIdStartWithinYearOutput { get; set; }
        public Nullable<int> HistoricFworkCodeOutput { get; set; }
        public Nullable<bool> HistoricLearner1618AtStartOutput { get; set; }
        public Nullable<decimal> HistoricPMRAmountOutput { get; set; }
        public Nullable<System.DateTime> HistoricProgrammeStartDateIgnorePathwayOutput { get; set; }
        public Nullable<System.DateTime> HistoricProgrammeStartDateMatchPathwayOutput { get; set; }
        public Nullable<int> HistoricProgTypeOutput { get; set; }
        public Nullable<int> HistoricPwayCodeOutput { get; set; }
        public Nullable<int> HistoricSTDCodeOutput { get; set; }
        public Nullable<decimal> HistoricTNP1Output { get; set; }
        public Nullable<decimal> HistoricTNP2Output { get; set; }
        public Nullable<decimal> HistoricTNP3Output { get; set; }
        public Nullable<decimal> HistoricTNP4Output { get; set; }
        public Nullable<decimal> HistoricTotal1618UpliftPaymentsInTheYear { get; set; }
        public Nullable<decimal> HistoricTotalProgAimPaymentsInTheYear { get; set; }
        public Nullable<long> HistoricULNOutput { get; set; }
        public Nullable<System.DateTime> HistoricUptoEndDateOutput { get; set; }
        public Nullable<decimal> HistoricVirtualTNP3EndofThisYearOutput { get; set; }
        public Nullable<decimal> HistoricVirtualTNP4EndofThisYearOutput { get; set; }
        public Nullable<System.DateTime> HistoricLearnDelProgEarliestACT2DateOutput { get; set; }
    }
}
