//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILRLegacy.DataStore._1718EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEC_ApprenticeshipPriceEpisode_Period
    {
        public int UKPRN { get; set; }
        public string LearnRefNumber { get; set; }
        public string PriceEpisodeIdentifier { get; set; }
        public int Period { get; set; }
        public Nullable<decimal> PriceEpisodeApplic1618FrameworkUpliftBalancing { get; set; }
        public Nullable<decimal> PriceEpisodeApplic1618FrameworkUpliftCompletionPayment { get; set; }
        public Nullable<decimal> PriceEpisodeApplic1618FrameworkUpliftOnProgPayment { get; set; }
        public Nullable<decimal> PriceEpisodeBalancePayment { get; set; }
        public Nullable<decimal> PriceEpisodeBalanceValue { get; set; }
        public Nullable<decimal> PriceEpisodeCompletionPayment { get; set; }
        public Nullable<decimal> PriceEpisodeFirstDisadvantagePayment { get; set; }
        public Nullable<decimal> PriceEpisodeFirstEmp1618Pay { get; set; }
        public Nullable<decimal> PriceEpisodeFirstProv1618Pay { get; set; }
        public Nullable<int> PriceEpisodeInstalmentsThisPeriod { get; set; }
        public Nullable<int> PriceEpisodeLevyNonPayInd { get; set; }
        public Nullable<decimal> PriceEpisodeLSFCash { get; set; }
        public Nullable<decimal> PriceEpisodeOnProgPayment { get; set; }
        public Nullable<decimal> PriceEpisodeProgFundIndMaxEmpCont { get; set; }
        public Nullable<decimal> PriceEpisodeProgFundIndMinCoInvest { get; set; }
        public Nullable<decimal> PriceEpisodeSecondDisadvantagePayment { get; set; }
        public Nullable<decimal> PriceEpisodeSecondEmp1618Pay { get; set; }
        public Nullable<decimal> PriceEpisodeSecondProv1618Pay { get; set; }
        public Nullable<decimal> PriceEpisodeSFAContribPct { get; set; }
        public Nullable<decimal> PriceEpisodeTotProgFunding { get; set; }
    }
}
