//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILRLegacy.DataStore._1718EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DV_Learner
    {
        public int UKPRN { get; set; }
        public string LearnRefNumber { get; set; }
        public Nullable<int> Learn_3rdSector { get; set; }
        public Nullable<int> Learn_Active { get; set; }
        public Nullable<int> Learn_ActiveJan { get; set; }
        public Nullable<int> Learn_ActiveNov { get; set; }
        public Nullable<int> Learn_ActiveOct { get; set; }
        public Nullable<int> Learn_Age31Aug { get; set; }
        public Nullable<int> Learn_BasicSkill { get; set; }
        public Nullable<int> Learn_EmpStatFDL { get; set; }
        public Nullable<int> Learn_EmpStatPrior { get; set; }
        public Nullable<int> Learn_FirstFullLevel2 { get; set; }
        public Nullable<int> Learn_FirstFullLevel2Ach { get; set; }
        public Nullable<int> Learn_FirstFullLevel3 { get; set; }
        public Nullable<int> Learn_FirstFullLevel3Ach { get; set; }
        public Nullable<int> Learn_FullLevel2 { get; set; }
        public Nullable<int> Learn_FullLevel2Ach { get; set; }
        public Nullable<int> Learn_FullLevel3 { get; set; }
        public Nullable<int> Learn_FullLevel3Ach { get; set; }
        public Nullable<int> Learn_FundAgency { get; set; }
        public Nullable<int> Learn_FundingSource { get; set; }
        public Nullable<int> Learn_FundPrvYr { get; set; }
        public Nullable<int> Learn_ILAcMonth1 { get; set; }
        public Nullable<int> Learn_ILAcMonth10 { get; set; }
        public Nullable<int> Learn_ILAcMonth11 { get; set; }
        public Nullable<int> Learn_ILAcMonth12 { get; set; }
        public Nullable<int> Learn_ILAcMonth2 { get; set; }
        public Nullable<int> Learn_ILAcMonth3 { get; set; }
        public Nullable<int> Learn_ILAcMonth4 { get; set; }
        public Nullable<int> Learn_ILAcMonth5 { get; set; }
        public Nullable<int> Learn_ILAcMonth6 { get; set; }
        public Nullable<int> Learn_ILAcMonth7 { get; set; }
        public Nullable<int> Learn_ILAcMonth8 { get; set; }
        public Nullable<int> Learn_ILAcMonth9 { get; set; }
        public Nullable<int> Learn_ILCurrAcYr { get; set; }
        public Nullable<int> Learn_LargeEmployer { get; set; }
        public Nullable<int> Learn_LenEmp { get; set; }
        public Nullable<int> Learn_LenUnemp { get; set; }
        public Nullable<int> Learn_LrnAimRecords { get; set; }
        public Nullable<int> Learn_ModeAttPlanHrs { get; set; }
        public Nullable<int> Learn_NotionLev { get; set; }
        public Nullable<int> Learn_NotionLevV2 { get; set; }
        public Nullable<int> Learn_OLASS { get; set; }
        public Nullable<int> Learn_PrefMethContact { get; set; }
        public Nullable<int> Learn_PrimaryLLDD { get; set; }
        public Nullable<int> Learn_PriorEducationStatus { get; set; }
        public Nullable<int> Learn_UnempBenFDL { get; set; }
        public Nullable<int> Learn_UnempBenPrior { get; set; }
        public Nullable<decimal> Learn_Uplift1516EFA { get; set; }
        public Nullable<decimal> Learn_Uplift1516SFA { get; set; }
    }
}
