//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILRLegacy.DataStore._1718EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LearningDelivery
    {
        public int UKPRN { get; set; }
        public string LearnRefNumber { get; set; }
        public int AimSeqNumber { get; set; }
        public Nullable<System.DateTime> ProgStandardStartDate { get; set; }
        public string FundLine { get; set; }
        public Nullable<decimal> MathEngAimValue { get; set; }
        public Nullable<int> PlannedNumOnProgInstalm { get; set; }
        public Nullable<decimal> LearnSuppFundCash { get; set; }
        public Nullable<System.DateTime> AdjProgStartDate { get; set; }
        public Nullable<bool> LearnSuppFund { get; set; }
        public Nullable<decimal> MathEngOnProgPayment { get; set; }
        public Nullable<int> InstPerPeriod { get; set; }
        public Nullable<decimal> SmallBusPayment { get; set; }
        public Nullable<decimal> YoungAppSecondPayment { get; set; }
        public Nullable<decimal> CoreGovContPayment { get; set; }
        public Nullable<bool> YoungAppEligible { get; set; }
        public Nullable<bool> SmallBusEligible { get; set; }
        public Nullable<int> MathEngOnProgPct { get; set; }
        public Nullable<int> AgeStandardStart { get; set; }
        public Nullable<System.DateTime> YoungAppSecondThresholdDate { get; set; }
        public Nullable<int> EmpIdFirstDayStandard { get; set; }
        public Nullable<int> EmpIdFirstYoungAppDate { get; set; }
        public Nullable<int> EmpIdSecondYoungAppDate { get; set; }
        public Nullable<int> EmpIdSmallBusDate { get; set; }
        public Nullable<System.DateTime> YoungAppFirstThresholdDate { get; set; }
        public Nullable<System.DateTime> AchApplicDate { get; set; }
        public Nullable<bool> AchEligible { get; set; }
        public Nullable<bool> Achieved { get; set; }
        public Nullable<decimal> AchievementApplicVal { get; set; }
        public Nullable<decimal> AchPayment { get; set; }
        public Nullable<int> ActualNumInstalm { get; set; }
        public Nullable<long> CombinedAdjProp { get; set; }
        public Nullable<int> EmpIdAchDate { get; set; }
        public Nullable<int> LearnDelDaysIL { get; set; }
        public Nullable<int> LearnDelStandardAccDaysIL { get; set; }
        public Nullable<int> LearnDelStandardPrevAccDaysIL { get; set; }
        public Nullable<int> LearnDelStandardTotalDaysIL { get; set; }
        public Nullable<int> ActualDaysIL { get; set; }
        public Nullable<decimal> MathEngBalPayment { get; set; }
        public Nullable<long> MathEngBalPct { get; set; }
        public Nullable<bool> MathEngLSFFundStart { get; set; }
        public Nullable<int> PlannedTotalDaysIL { get; set; }
        public Nullable<int> MathEngLSFThresholdDays { get; set; }
        public Nullable<int> OutstandNumOnProgInstalm { get; set; }
        public Nullable<decimal> SmallBusApplicVal { get; set; }
        public Nullable<int> SmallBusStatusFirstDayStandard { get; set; }
        public Nullable<int> SmallBusStatusThreshold { get; set; }
        public Nullable<decimal> YoungAppApplicVal { get; set; }
        public Nullable<long> CoreGovContCapApplicVal { get; set; }
        public Nullable<decimal> CoreGovContUncapped { get; set; }
        public Nullable<System.DateTime> ApplicFundValDate { get; set; }
        public Nullable<decimal> YoungAppFirstPayment { get; set; }
        public Nullable<decimal> YoungAppPayment { get; set; }
    }
}
